
# from langchain_openai import ChatOpenAI
import pandas as pd
import json


prompt = """\
I want you to act as a question and answer wiki. 
Create json object that has an ‘input_text’ key and ‘answer’ key. The ‘input_text’ will be a question generated by you. The ‘answer’ key will be the answer to the question generated. 
Generate 100 rows that has the top questions searched by users on google or any search engine. 


Note:
 — Keep the answer short and concise
- Keep the question simple
- The json object can have ‘context’ key that provides more context to the question. 
 
  - Generate 100 rows
"""

# query = ChatOpenAI(openai_api_key=OPEN_API_KEY).invoke(prompt)
# print(query)

def convert_json_to_csv():
    import json
    # print(query)
    f = open('/home/azureuser/quotient/dataset/dataset_llm_generated.json')

    data = json.load(f)
    df = pd.DataFrame(data)
    csv_file = 'dataset_case3.csv'
    df.to_csv(csv_file, index=False)  

convert_json_to_csv()


